spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/samdb
    username: postgres
    password: hjg1920
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ynhuang
      auto-commit: true
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 20000
      register-mbeans: true
nacos:
  config:
    server-addr:
       192.168.33.1:8848


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG